public class ExportPlannerModel
{
    public int open_stack_check { get; set; }
    public int close_stack_check { get; set; }
    public string id { get; set; }
    public string shipment_number { get; set; }
    public string booking_reference { get; set; }
    public string customer { get; set; }
    public string commodity { get; set; }
    public string Whs { get; set; }
    public string empty_release_date { get; set; }
    public string vessel { get; set; }
    public string line { get; set; }
    public string Voy { get; set; }
    public string Qty20s { get; set; }
    public string Qty40s { get; set; }
    public int Qty_FCL { get; set; }
    public int MTY_Rec { get; set; }
    public int OS_MTY { get; set; }
    public string Pack { get; set; }
    public int OS_Pack { get; set; }
    public string Disp { get; set; }
    public int AV { get; set; }
    public string FCL_In { get; set; }
    public string Stack { get; set; }
    public int OS_Stack { get; set; }
    public string transport_mode { get; set; }
    public string berth { get; set; }
    public string transnet_stack_open { get; set; }
    public string transnet_stack_close { get; set; }
    public string bos_stack_open { get; set; }
    public string bos_stack_close { get; set; }
    public string ttsc { get; set; }
    public string Qty_in_DEM { get; set; }
    public string Qty_at_risk { get; set; }
    public int Estimated_DEM_cost { get; set; }
    public string controller { get; set; }
    public string order_date { get; set; }
    public string order_number { get; set; }
    public string contact_person { get; set; }
    public string calc_type { get; set; }
    public string finance_bank { get; set; }
    public string hold_dispatch { get; set; }
    public string pickup_depot { get; set; }
    public string booking_status { get; set; }
    public string comment { get; set; }
    public string transport_mode_dispatch { get; set; }
}
